/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContasBancariasRouteImport } from './routes/_authenticated/contas-bancarias'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCentrosDeCustoRouteImport } from './routes/_authenticated/centros-de-custo'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedAssociadosIrtdpjRouteImport } from './routes/_authenticated/associados-irtdpj'
import { Route as AuthenticatedContasAPagarIndexRouteImport } from './routes/_authenticated/contas-a-pagar/index'
import { Route as AuthenticatedContasAPagarNovaRouteImport } from './routes/_authenticated/contas-a-pagar/nova'
import { Route as AuthenticatedContasAPagarIdRouteImport } from './routes/_authenticated/contas-a-pagar/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContasBancariasRoute =
  AuthenticatedContasBancariasRouteImport.update({
    id: '/contas-bancarias',
    path: '/contas-bancarias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCentrosDeCustoRoute =
  AuthenticatedCentrosDeCustoRouteImport.update({
    id: '/centros-de-custo',
    path: '/centros-de-custo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssociadosIrtdpjRoute =
  AuthenticatedAssociadosIrtdpjRouteImport.update({
    id: '/associados-irtdpj',
    path: '/associados-irtdpj',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContasAPagarIndexRoute =
  AuthenticatedContasAPagarIndexRouteImport.update({
    id: '/contas-a-pagar/',
    path: '/contas-a-pagar/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContasAPagarNovaRoute =
  AuthenticatedContasAPagarNovaRouteImport.update({
    id: '/contas-a-pagar/nova',
    path: '/contas-a-pagar/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContasAPagarIdRoute =
  AuthenticatedContasAPagarIdRouteImport.update({
    id: '/contas-a-pagar/$id',
    path: '/contas-a-pagar/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/associados-irtdpj': typeof AuthenticatedAssociadosIrtdpjRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/centros-de-custo': typeof AuthenticatedCentrosDeCustoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/contas-a-pagar/$id': typeof AuthenticatedContasAPagarIdRoute
  '/contas-a-pagar/nova': typeof AuthenticatedContasAPagarNovaRoute
  '/contas-a-pagar/': typeof AuthenticatedContasAPagarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/associados-irtdpj': typeof AuthenticatedAssociadosIrtdpjRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/centros-de-custo': typeof AuthenticatedCentrosDeCustoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/contas-a-pagar/$id': typeof AuthenticatedContasAPagarIdRoute
  '/contas-a-pagar/nova': typeof AuthenticatedContasAPagarNovaRoute
  '/contas-a-pagar': typeof AuthenticatedContasAPagarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/associados-irtdpj': typeof AuthenticatedAssociadosIrtdpjRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/centros-de-custo': typeof AuthenticatedCentrosDeCustoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/contas-a-pagar/$id': typeof AuthenticatedContasAPagarIdRoute
  '/_authenticated/contas-a-pagar/nova': typeof AuthenticatedContasAPagarNovaRoute
  '/_authenticated/contas-a-pagar/': typeof AuthenticatedContasAPagarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/associados-irtdpj'
    | '/categorias'
    | '/centros-de-custo'
    | '/configuracoes'
    | '/contas-bancarias'
    | '/dashboard'
    | '/fornecedores'
    | '/relatorios'
    | '/contas-a-pagar/$id'
    | '/contas-a-pagar/nova'
    | '/contas-a-pagar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/associados-irtdpj'
    | '/categorias'
    | '/centros-de-custo'
    | '/configuracoes'
    | '/contas-bancarias'
    | '/dashboard'
    | '/fornecedores'
    | '/relatorios'
    | '/contas-a-pagar/$id'
    | '/contas-a-pagar/nova'
    | '/contas-a-pagar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/associados-irtdpj'
    | '/_authenticated/categorias'
    | '/_authenticated/centros-de-custo'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas-bancarias'
    | '/_authenticated/dashboard'
    | '/_authenticated/fornecedores'
    | '/_authenticated/relatorios'
    | '/_authenticated/contas-a-pagar/$id'
    | '/_authenticated/contas-a-pagar/nova'
    | '/_authenticated/contas-a-pagar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-bancarias': {
      id: '/_authenticated/contas-bancarias'
      path: '/contas-bancarias'
      fullPath: '/contas-bancarias'
      preLoaderRoute: typeof AuthenticatedContasBancariasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/centros-de-custo': {
      id: '/_authenticated/centros-de-custo'
      path: '/centros-de-custo'
      fullPath: '/centros-de-custo'
      preLoaderRoute: typeof AuthenticatedCentrosDeCustoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/associados-irtdpj': {
      id: '/_authenticated/associados-irtdpj'
      path: '/associados-irtdpj'
      fullPath: '/associados-irtdpj'
      preLoaderRoute: typeof AuthenticatedAssociadosIrtdpjRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-a-pagar/': {
      id: '/_authenticated/contas-a-pagar/'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar/'
      preLoaderRoute: typeof AuthenticatedContasAPagarIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-a-pagar/nova': {
      id: '/_authenticated/contas-a-pagar/nova'
      path: '/contas-a-pagar/nova'
      fullPath: '/contas-a-pagar/nova'
      preLoaderRoute: typeof AuthenticatedContasAPagarNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-a-pagar/$id': {
      id: '/_authenticated/contas-a-pagar/$id'
      path: '/contas-a-pagar/$id'
      fullPath: '/contas-a-pagar/$id'
      preLoaderRoute: typeof AuthenticatedContasAPagarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssociadosIrtdpjRoute: typeof AuthenticatedAssociadosIrtdpjRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedCentrosDeCustoRoute: typeof AuthenticatedCentrosDeCustoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContasBancariasRoute: typeof AuthenticatedContasBancariasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedContasAPagarIdRoute: typeof AuthenticatedContasAPagarIdRoute
  AuthenticatedContasAPagarNovaRoute: typeof AuthenticatedContasAPagarNovaRoute
  AuthenticatedContasAPagarIndexRoute: typeof AuthenticatedContasAPagarIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssociadosIrtdpjRoute: AuthenticatedAssociadosIrtdpjRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedCentrosDeCustoRoute: AuthenticatedCentrosDeCustoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContasBancariasRoute: AuthenticatedContasBancariasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedContasAPagarIdRoute: AuthenticatedContasAPagarIdRoute,
  AuthenticatedContasAPagarNovaRoute: AuthenticatedContasAPagarNovaRoute,
  AuthenticatedContasAPagarIndexRoute: AuthenticatedContasAPagarIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
